# Generated by Django 6.1.1 on 2026-09-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
            preserve_default=False,
        ),
    ]
